language: ruby
bundler_args: --without no_ci
before_install:
  - "gem update --system"
  - "gem update bundler"
script:
  - "bundle exec rspec"
os:
  - linux
  - osx
rvm:
  - 2.3.8
  - 2.4.7
  - 2.6.4
matrix:
  include:
    - rvm: "2.3.8"
      script: "bundle exec rubocop"
branches:
  only:
    - master
    - v4-stable
