sudo: required

language: ruby

services:
  - docker

before_install:
  - docker-compose build

script: "docker run -v $PWD:/usr/src/backup -it backup_runner:latest bundle exec rspec ./spec/"

branches:
  only:
    - feature/docker-testing
