language: ruby
bundler_args: --without no_ci
before_install:
  - "gem update --system"
  - "gem update bundler"
script:
  - "bundle exec rspec"
os:
  - linux
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
matrix:
  include:
    - rvm: 2.3
      script: "bundle exec rubocop"
    - rvm: 2.6
      os: osx
branches:
  only:
    - master
    - v4-stable
