language: ruby
bundler_args: --without no_ci
before_install:
  - "gem update --system"
  - "gem update bundler"
script:
  - "bundle exec rspec"
os:
  - linux
  - osx
rvm:
  - 2.3.5
  - 2.4.3
  - 2.6.3
matrix:
  include:
    - rvm: "2.3.5"
      script: "bundle exec rubocop"
branches:
  only:
    - master
    - v4-stable
