sudo: required

language: ruby

services:
  - docker

before_install:
  - docker-compose build

script: "bundle exec rake docker:test:all"

branches:
  only:
    - master
    - develop
    - feature/docker-testing
