language: ruby
bundler_args: --without no_ci
before_install:
  - "gem update --system"
  - "gem update bundler"
script:
  - "bundle exec rspec"
os:
  - linux
  - osx
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
matrix:
  include:
    - rvm: "2.3.7"
      script: "bundle exec rubocop"
branches:
  only:
    - master
    - develop
    - v4-stable
