version: '2'

services:
  runner:
    build: .
    command: /bin/bash
    volumes:
      - ".:/usr/src/backup"
    links:
      - mongo
      - mysql
      - postgres
      - redis
  mongo:
    image: mongo:2.4.10
    ports:
      - "27017:27017"
  mysql:
    image: mysql:5.5.53
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
  postgres:
    image: postgres:9.4.9
    ports:
      - "5432:5432"
  redis:
    image: redis:2.8.17
    ports:
      - "6379:6379"
